



import React, { useState, useCallback } from 'react';
import { generateImage } from '../services/geminiService';
import { AspectRatio } from '../types';
import { ImageIcon } from '../components/icons/ImageIcon';
import { SparklesIcon } from '../components/icons/SparklesIcon';

const aspectRatios: AspectRatio[] = ["1:1", "16:9", "9:16", "4:3", "3:4"];

const ImageGenerator: React.FC = () => {
    const [prompt, setPrompt] = useState('');
    const [aspectRatio, setAspectRatio] = useState<AspectRatio>('1:1');
    const [isLoading, setIsLoading] = useState(false);
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);

    const handleGenerate = useCallback(async () => {
        if (!prompt.trim()) {
            setError('Please enter a prompt.');
            return;
        }
        setIsLoading(true);
        setGeneratedImage(null);
        setError(null);

        try {
            const imageBytes = await generateImage(prompt, aspectRatio);
            setGeneratedImage(`data:image/jpeg;base64,${imageBytes}`);
        } catch (err) {
            console.error(err);
            setError('Failed to generate image. Please try again.');
        } finally {
            setIsLoading(false);
        }
    }, [prompt, aspectRatio]);

    return (
        <div className="max-w-4xl mx-auto flex flex-col items-center gap-6">
            <div className="w-full bg-gray-800/50 p-6 rounded-xl shadow-lg border border-gray-700">
                <h2 className="text-lg font-semibold mb-4 text-cyan-300">Image Generation Prompt</h2>
                <textarea
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    placeholder="e.g., A majestic lion wearing a crown, cinematic lighting, hyperrealistic"
                    className="w-full bg-gray-700/50 p-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500 transition-shadow text-gray-200"
                    rows={3}
                />
                <div className="mt-4">
                    <label className="block text-sm font-medium text-gray-400 mb-2">Aspect Ratio</label>
                    <div className="flex flex-wrap gap-2">
                        {aspectRatios.map(ar => (
                            <button
                                key={ar}
                                onClick={() => setAspectRatio(ar)}
                                className={`px-4 py-2 text-sm rounded-md transition-colors ${aspectRatio === ar ? 'bg-cyan-600 text-white font-semibold' : 'bg-gray-700 hover:bg-gray-600 text-gray-300'}`}
                            >
                                {ar}
                            </button>
                        ))}
                    </div>
                </div>
                 <button
                    onClick={handleGenerate}
                    disabled={isLoading}
                    className="mt-6 w-full flex items-center justify-center gap-2 bg-gradient-to-r from-cyan-500 to-purple-600 text-white font-bold py-3 px-4 rounded-lg hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isLoading ? (
                         <>
                            <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                            Generating...
                         </>
                    ) : (
                        <>
                            <SparklesIcon className="w-5 h-5" />
                            Generate Image
                        </>
                    )}
                </button>
            </div>
            
            {error && <div className="text-red-400 bg-red-900/50 p-3 rounded-lg w-full text-center">{error}</div>}
            
            <div className="w-full min-h-[300px] bg-gray-800/30 border-2 border-dashed border-gray-600 rounded-xl flex items-center justify-center p-4">
                {isLoading ? (
                    <div className="text-center text-gray-400">
                        <div className="w-8 h-8 mx-auto border-4 border-cyan-400 border-t-transparent rounded-full animate-spin mb-4"></div>
                        <p>Red is creating your masterpiece...</p>
                    </div>
                ) : generatedImage ? (
                    <img src={generatedImage} alt="Generated by Red" className="max-w-full max-h-[70vh] rounded-lg shadow-2xl" />
                ) : (
                    <div className="text-center text-gray-500">
                        <ImageIcon className="w-16 h-16 mx-auto mb-4" />
                        <p>Your generated image will appear here</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ImageGenerator;